name: gibbs_states_trainer
data:
  distribution: classification
  num_classes: 4
  num_features: 100
  dimension: 2
  density: 0.5
  temperature: 1.0
  y_range: [0, 3]

model:
  type: classification
  layers: 2
  wires: 5
  ae_type: LL

training:
  trainer: classification
  learning_rate: 0.01
  batch_size: 4
  epochs: 150
  training_samples: 100
