name: sinusoidal_trainer
data:
  distribution: sinusoidal
  x_range: [-5, 5]
  y_range: [-1, 1]

model:
  type: supervised
  layers: 2
  wires: 5
  ae_type: LL

training:
  trainer: regression
  learning_rate: 0.01
  batch_size: 33
  epochs: 150
  training_samples: 99
